### ISSUE TITLE
On duplicate tab detected -> close tab automatically stopped working on Chrome

### ISSUE THREAD

**Issue by folmert** [Peuj/duplicate-tabs-closer#38]
Steps to reproduce:
1. Open one tab with google.com
2. Open one tab with github.com
3. Open third tab with google.com
4. Third tab is closed, but google.com tab is not activated

Chrome Version 83.0.4103.61

I've noticed this behavior yesterday. This used to work at least last week.

**Comment by Peuj** [comment]
I cannot reproduce your problem.
Maybe I've fixed something in the latest version 3.5.2.
Let me know when it's available.

**Comment by tekko** [comment]
It seems like there is a problem with "keep newer". It doesn't activate the new tab.
"keep older" seems to work when "keep newer" doesn't.

**Comment by Turri81** [comment]
I was able to reproduce the problem with Chrome 83.0.4103.61 and Plugin Version 3.5.3.
In my case it jumps not to the "remaining" Tab, it jumps back to last active Tab.

**Comment by folmert** [comment]
Seems to work for me again.
Chrome 84.0.4147.105, Plugin 3.5.3

**Comment by folmert** [comment]
Well it's still happening, sometimes it doesn't work with many tabs opened :/

**Comment by Peuj** [comment]
I'm modifying some parts on the code.
I'll check this and let you know

**Comment by shemayas** [comment]
The same scenario is not working for me also, Version 103.0.5060.53

Edit

After playing around I saw that it's not working specifically for my wanted use case.
I use React and when I `npm run start` a new tab opens but the extension does not identify it, otherways manually opening a new duplicated tab it's working

**Comment by Peuj** [comment]
The MV3 migration in v4.0.0 reworks the background script and async handling that affected this behavior on Chrome. Please test with v4.0.0 and reopen if activate remaining tab still doesn't work.
